spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100
  datasource:
    url: jdbc:mysql://localhost:3306/project_artisan_test
    username: root
    password: password