spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev


spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_artisan_test
    username: root
    password: password

---
spring.config.activate.on-profile: prod

spring:
  jpa:
    properties:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://artisan-rds.c9682ysku7lv.ap-northeast-2.rds.amazonaws.com/artisan_prod
    username: artisan-service
    password: e2rQPyvKxAQD19VCqrSvDOq


