
spring:

  config:
    import:
      - mysql-db.yml
      - api-security.yml
      - infra-oauth-github.yml


  profiles:

    active: local-dev
    group:
      local: local
      local-dev: local-dev
      prod: prod
