name: Spring CI

on:

  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지터리 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.TOKEN }}
  
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./artisan
  
      - name: Run gradlew command
        run: ./gradlew artisan-api:build
        working-directory: ./artisan

      - name: Make zip file
        run: zip -r $GITHUB_SHA.zip ./artisan/artisan-api/build/libs/*.jar ./appspec.yml ./scripts/deploy.sh
            
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{secrets.AWS_BUCKET_NAME}}/$GITHUB_SHA.zip
        
      - name: Code Deploy
        run: aws deploy create-deployment --application-name artisan-cicd --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name artisan-cicde-deploy-group --s3-location bucket=${{secrets.AWS_BUCKET_NAME}},bundleType=zip,key=$GITHUB_SHA.zip
  